### ISSUE TITLE
distutils package is deprecated and slated for removal in Python 3.12. 

### ISSUE THREAD

**Issue by ewadii** [gluster/gstatus#67]
Running gstatus script throws a DeprecationWarning

/usr/bin/gstatus/main.py:7: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives

gstatus --version : gstatus v1.0.8
Dist : Ubuntu 22.04.1 LTS
python3 version : Python 3.10.4

**Comment by osztrovszkyzs-ahrt** [comment]
gstatus v1.0.8
Python 3.11.2
Debian 12.1

same issue

**Comment by CluelessTechnologist** [comment]
This message causes the [zabbix monitoring](https://github.com/alt-dima/zabbix-glusterfs) to stop working since it uses the output of `gstatus`.

I had to add `ignore::DeprecationWarning` to the env line in `/usr/bin/gstatus` after installing it from the install script. Not best practice but it solves the issue I was having with `gstatus_discovery.py`. 

    #!/usr/bin/env -S python3 -W ignore::DeprecationWarning

**Comment by Apollon77** [comment]
Python 3.12 is generally out there and will be in OS releases soon ... any chance for a fix?

**Comment by aravindavk** [comment]
Sure. Expect a patch and release in this month.
